### ISSUE TITLE
Mailmate bundle nukes entire TP doc — *sometimes*

### ISSUE THREAD

**Issue by tbfld** [pslobo/Scripts#5]
Just like it says on the tin: _sometimes_ the Mailmate bundle deletes the entire TP doc it's writing to, leaving it blank. Fortunately, I'm careful, so it's been an 'issue' not a problem; unfortunately, I haven't figured out what specific circumstances determine that outcome. Aside from that, this is a really nice piece of software.

**Comment by pslobo** [comment]
Thanks for pointing this out. I'll try look into it and see what is causing this problem.

**Comment by pslobo** [comment]
Hey @tbfld could you provide a little more info, more specifically:

- When does it nuke the file? When using **Send to Default** or, **Send to Front Most**

**Comment by tbfld** [comment]
I haven't been able to reproduce it, and it hasn't just happened. I'll try, and if I can't do so in the next week probably best to mark it resolved. Thanks for following up.

**Comment by pslobo** [comment]
Either way, I think it may be best to create a backup (hidden file with same name maybe) when altering the TP file. That way, if something goes wrong, restoring should be a trivial matter. If all is good, next action overwrites the backup.

Still need to give this a little more thought though, but will probably be best.
